spring:
  application:
    name: spring-batch-boot
  batch:
    job:
      name: systemInfiltrationJob
#       name: serverRoomControlJob
#      name: systemMonitoringJob
#      name: systemDestructionJob
#      name: terminatorJob
#      name: processTerminatorJob
#      name: deleteOldFilesJob
#      name: systemTerminationSimulationJob
#      name: zombieCleanupJob

